markdown: redcarpet
pygments: true
paginate: 10
excerpt_separator: \n\n

safe:  false

#Site config
title: 徐不猛的程序之道
subtitle: 子曰：君子惠而不费，劳而不怨，欲而不贪，泰而不骄，威而不猛！
description: 徐不猛的程序之道，你懂的。
keywords: 徐不猛
#url: http://localhost:4000
url: http://www.xubumeng.com
feed: /atom.xml
favicon: /images/favicon.ico

#Nav config
nav:
  - text: 徐不猛
    url: /index.html
  - text: Categories 
    url: /categories.html
  - text: Archives
    url: /archives.html
  - text: About
    url: /contact.html
  - text: Links
    url: /links.html
  - text: 声明(Warning)
    url: /warning.html

#Author config
author:
    name: Amon
    email: gosuxm@gmail.com
    imageLink: https://2.gravatar.com/avatar/615724a207b98b15161ba22985a512df?d=https%3A%2F%2Fidenticons.github.com%2F75fb4616b7c8511387f87dad13b34da4.png&s=440
    simpleIntro:  <img src="/images/qrcode.jpg" alt="想要看天气、看笑话、看妹子，找各种应用工具，就扫一扫关注公众号：徐不猛的程序之道，或者搜索"xubumeng"." width="100px" height="100px" /><br>Amon者,庚午年生人，楚弦人士，自幼贪玩好动喜折腾，仰天资一二故成绩甚好。  然至高中之时，误入Computer之迷途，自此一发不可收拾矣。虽金榜无名，却未尝有悔意。终学于此。   待学成出山，就业南国一隅，纵横四余载，愈觉岁月匆匆。每日书影以学，仍感光阴之不足。 虽无悬梁凿壁之勇，盖因惧房东无德；虽无囊萤映雪之聪，盖因身处南国都市。   回首余已二十有四，事业未成。幸得佳人伴我孤灯零影之日，感极涕零！
    detailIntro:
      <p>
      车水马龙非我意，远山近水乃吾心。<br>
      每见腾空尾气起，遥思故乡炊烟升。<br>
      披星带月二三年，吾以汗泪付青春。<br>
      幸得佳人长相伴，早日衣锦立功勋。<br><br>
      <h3>写在最后：</h3><br>
      程序猿一只，涉及iOS,Android,Java,Flex,Python,C,C++,擅长移动开发、Web开发，服务器开发。<br>
      </p>

#Follow me, you can choose your icon by http://fortawesome.github.io/Font-Awesome/icons/#brand
follow:
  - class: icon-rss
    url: /atom.xml
  - class: icon-github-alt
    url: http://github.com/xumeng

#Links
customLinks:
  - item:
    - text: Jekyll
      url: http://jekyllrb.com
    - text: Github
      url: http://github.com
    message: Blog
  - item:
    - text: LeeAmo
      url: http://leeamo.com
    message: Friends

#googleAnaly, your id link UA-12345678-X
googleAnaly:
  config: true
  id: UA-40169250-1

#comment config
duoshuo:
  config: true
  id: amon